### ISSUE TITLE
Can not find  'F:\\ComfyUI\\fonts'

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [bash-j/mikey_nodes#5]
I update the UI and all custom nodes every morning and have just hit this error after updating 30 mins ago:

```
FETCH DATA from: F:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\Users\farre\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\farre\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\Users\farre\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "F:\ComfyUI\server.py", line 43, in cache_control
    response: web.Response = await handler(request)
  File "F:\ComfyUI\server.py", line 407, in get_object_info
    out[x] = node_info(x)
  File "F:\ComfyUI\server.py", line 386, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "F:\ComfyUI\custom_nodes\mikey_nodes\mikey_nodes.py", line 2165, in INPUT_TYPES
    cls.font_files = [os.path.join(cls.font_dir, f) for f in os.listdir(cls.font_dir) if os.path.isfile(os.path.join(cls.font_dir, f))]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\ComfyUI\\fonts'
```

**Comment by GalaxyTimeMachine** [comment]
I reset to 2ff34879665508ee5c84da8d4f4b9ad404c65732 and the error has gone.

**Comment by bash-j** [comment]
@GalaxyTimeMachine Sorry for the inconvenience. I have modified the node that was causing the issue. If you git pull it, hopefully that fixes the problem for you. Let me know if you have any further issues.

**Comment by GalaxyTimeMachine** [comment]
That works, thank you!
